name: 📝 Update Blog Posts from One-Hundred-Articles

on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v3

      - name: Clone Articles Repo
        uses: actions/checkout@v3
        with:
          repository: bilelsalemdev/one-hundred-articles
          path: articles

      - name: Extract Articles and Update README
        run: |
          cd articles

          # Get 5 latest markdown files in root
          files=$(ls -t *.md | head -n 5)

          markdown=""
          for file in $files; do
            title=$(head -n 1 "$file" | sed 's/^# //')
            link="https://github.com/bilelsalemdev/one-hundred-articles/blob/main/$file"
            markdown="$markdown\n- [$title]($link)"
          done

          cd ..

          # Escape markdown for use in sed
          escaped_markdown=$(printf "%s\n" "$markdown" | sed 's/[&/\]/\\&/g')

          # Replace the BLOG-POST-LIST block
          sed -i "/<!-- BLOG-POST-LIST:START -->/,/<!-- BLOG-POST-LIST:END -->/c\\
<!-- BLOG-POST-LIST:START -->$escaped_markdown\\
<!-- BLOG-POST-LIST:END -->" README.md

          echo -e "✅ Generated Markdown:\n$markdown"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Update latest blog posts"
