name: 📝 Update Blog Posts from One-Hundred-Articles

on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v3

      - name: Clone Articles Repo
        uses: actions/checkout@v3
        with:
          repository: bilelsalemdev/one-hundred-articles
          path: articles

      - name: Extract Articles and Update README
        run: |
          cd articles

          # Get 5 latest markdown files in root
          files=$(ls -t *.md | head -n 5)

          markdown=""
          for file in $files; do
            title=$(head -n 1 "$file" | sed 's/^# //')
            link="https://github.com/bilelsalemdev/one-hundred-articles/blob/main/$file"
            markdown="$markdown\n- [$title]($link)"
          done

          cd ..

          # Replace BLOG-POST-LIST block in README
          awk '/<!-- BLOG-POST-LIST:START -->/{print;print markdown;found=1;next} /<!-- BLOG-POST-LIST:END -->/{found=0} !found' \
              markdown="$markdown" README.md > temp && mv temp README.md

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Update latest blog posts"
