name: 📝 Update Blog Posts from One-Hundred-Articles

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v3

      - name: Clone Articles Repo
        uses: actions/checkout@v3
        with:
          repository: bilelsalemdev/one-hundred-articles
          path: articles

      - name: Extract Articles and Update README
        run: |
          cd articles

          # Get 5 latest markdown files
          files=$(ls -t *.md | head -n 5)

          markdown=""
          for file in $files; do
            # Extract full filename (including spaces, punctuation) without .md
            title="${file%.md}"
            # Encode URL for GitHub link
            encoded_link=$(echo "$file" | jq -sRr @uri)
            link="https://github.com/bilelsalemdev/one-hundred-articles/blob/main/$encoded_link"
            markdown="${markdown}- [${title}](${link})\\n"
          done

          cd ..

          # Inject new content in README
          awk -v content="$markdown" '
            BEGIN { print_block=1 }
            {
              if ($0 ~ /<!-- BLOG-POST-LIST:START -->/) {
                print $0
                print_block=0
                next
              }
              if (print_block) {
                print $0
              }
              if ($0 ~ /<!-- BLOG-POST-LIST:END -->/) {
                print content
                print $0
                print_block=1
              }
            }
          ' README.md > README_temp.md

          mv README_temp.md README.md

          echo -e "✅ Injected Markdown:\n$markdown"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Update latest blog posts from filenames"
