name: 📝 Update Blog Posts from One-Hundred-Articles

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Profile Repo
        uses: actions/checkout@v3

      - name: Clone Articles Repo
        uses: actions/checkout@v3
        with:
          repository: bilelsalemdev/one-hundred-articles
          path: articles

      - name: Extract Articles and Update README
        run: |
          cd articles

          # Get latest 6 markdown files (by last modified date)
          readarray -d '' files < <(
            find . -maxdepth 1 -name "*.md" -print0 | \
            xargs -0 stat --format '%Y %n' | \
            sort -r | \
            head -n 6 | \
            cut -d' ' -f2- | \
            tr '\n' '\0'
          )

          markdown="<table><tr>"
          count=0

          for file in "${files[@]}"; do
            clean_name="${file#./}"
            title="${clean_name%.md}"
            encoded_link=$(jq -rn --arg x "$clean_name" '$x|@uri')
            link="https://github.com/bilelsalemdev/one-hundred-articles/blob/main/$encoded_link"

            # Extract brief preview (first 2 non-empty lines excluding markdown headers)
            preview=$(grep -vE '^\s*$|^#' "$file" | head -n 2 | tr -d '\r' | tr '\n' ' ')
            preview="${preview:0:220}..."  # limit to 220 chars

            markdown="${markdown}<td width=\"50%\" valign=\"top\"><strong><a href=\"$link\">$title</a></strong><br/><p>${preview}</p></td>"
            count=$((count + 1))

            if [ $((count % 2)) -eq 0 ]; then
              markdown="${markdown}</tr><tr>"
            fi
          done

          markdown="${markdown}</tr></table>"

          cd ..

          # Inject into README.md between the markers
          awk -v content="$markdown" '
            BEGIN { print_block=1 }
            {
              if ($0 ~ /<!-- BLOG-POST-LIST:START -->/) {
                print $0
                print_block=0
                next
              }
              if (print_block) {
                print $0
              }
              if ($0 ~ /<!-- BLOG-POST-LIST:END -->/) {
                print content
                print $0
                print_block=1
              }
            }
          ' README.md > README_temp.md

          mv README_temp.md README.md

          echo -e "✅ Injected Markdown:\n$markdown"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Update blog posts with titles and descriptions"
